<x-speedweek-layout><x-slot:title>Mijn Speedweek</x-slot:title>
@if(! $registration)<div class="rounded bg-zinc-900 p-6 border border-zinc-800">Nog geen registratie.</div>@else
<div class="grid gap-4 md:grid-cols-3"><section class="md:col-span-2 rounded bg-zinc-900 p-6 border border-zinc-800"><h3 class="text-2xl font-bold text-speedweek-400">Mijn Speedweek</h3><p class="mt-2">{{ $registration->event->name }} · {{ $registration->package->name }}</p><p class="mt-2"><span class="rounded bg-zinc-800 px-2 py-1">{{ $registration->status }}</span> <span class="rounded bg-speedweek-500 text-white px-2 py-1">{{ $registration->payment_status }}</span></p></section><section class="rounded bg-zinc-900 p-6 border border-zinc-800"><h3 class="font-bold">Contact</h3><p class="text-sm text-zinc-300 mt-2">Speedweek operations<br>info@speedweek.local<br>+31 000 000 000</p></section></div>
<div class="mt-4 grid gap-4 md:grid-cols-2 lg:grid-cols-3">
<section class="rounded bg-zinc-900 p-5 border border-zinc-800"><h4 class="font-semibold text-speedweek-400">Package features</h4><ul class="mt-2 text-sm space-y-1">@foreach($registration->package->features as $feature)<li>{{ $feature->included ? '✓' : '–' }} {{ $feature->label }}</li>@endforeach</ul></section>
<section class="rounded bg-zinc-900 p-5 border border-zinc-800"><h4 class="font-semibold text-speedweek-400">Open checklist</h4><p>{{ $registration->checklistItems->whereNull('completed_at')->count() }} open items</p><a class="text-speedweek-400" href="{{ route('dashboard.checklist') }}">Open checklist</a></section>
<section class="rounded bg-zinc-900 p-5 border border-zinc-800"><h4 class="font-semibold text-speedweek-400">Mijn motor</h4><p>{{ $registration->motorcycle?->brand ?? 'Niet ingevuld' }} {{ $registration->motorcycle?->model }}</p><a class="text-speedweek-400" href="{{ route('dashboard.motorcycle') }}">Bewerken</a></section>
<section class="rounded bg-zinc-900 p-5 border border-zinc-800"><h4 class="font-semibold text-speedweek-400">Bandenkeuze</h4><p>{{ $registration->tireRequest?->preferred_brand ?? 'Nog niet gekozen' }}</p><a class="text-speedweek-400" href="{{ route('dashboard.tires') }}">Bewerken</a></section>
<section class="rounded bg-zinc-900 p-5 border border-zinc-800"><h4 class="font-semibold text-speedweek-400">Reisinfo / hotelinfo</h4><p>{{ $registration->travelInfo?->outbound_flight_number ?? 'Nog niet ingevuld' }} · kamer {{ $registration->travelInfo?->hotel_room_number ?? 'TBD' }}</p><a class="text-speedweek-400" href="{{ route('dashboard.travel') }}">Bewerken</a></section>
<section class="rounded bg-zinc-900 p-5 border border-zinc-800"><h4 class="font-semibold text-speedweek-400">Belangrijke adressen</h4><p class="text-sm">{{ $registration->event->circuit_name }}<br>{{ $registration->event->circuit_address }}<br><br>{{ $registration->event->hotel_name }}<br>{{ $registration->event->hotel_address }}</p></section>
</div>
<section class="mt-4 rounded bg-zinc-900 p-5 border border-zinc-800"><h4 class="font-semibold text-speedweek-400">Programma</h4><div class="mt-2 grid gap-2">@foreach($registration->event->programmeItems->sortBy('starts_at')->take(6) as $item)<div class="flex justify-between border-b border-zinc-800 py-2"><span>{{ $item->title }}</span><span class="text-zinc-400">{{ $item->starts_at->format('d M H:i') }}</span></div>@endforeach</div><a class="text-speedweek-400" href="{{ route('dashboard.programme') }}">Volledig programma</a></section>
@endif
</x-speedweek-layout>
